### ISSUE TITLE
v0.2.0 Issues Found

### ISSUE THREAD

**Issue by mrcloudmustache** [cdot65/pan-scm-sdk#31]
Issues with version 0.2.0
* Missing AddressRequestModel. This model was helpful for validating data requests.
* Address list method raises an error when 'data' key is missing. If using filters and a single object is returned this causes an error. 
  * Previous version address list method was fine it just needed the response returned by default when no 'data' key was found.
  ```
  addresses = [AddressResponseModel(**item) for item in response.get("data", [response])]
  ```

**Comment by cdot65** [comment]
This is correct, we have moved away from using "Request" models in favor for CRUD-specific models that inherit a BaseModel.
