### ISSUE TITLE
Candidate Push feature is Missing

### ISSUE THREAD

**Issue by mrcloudmustache** [cdot65/pan-scm-sdk#74]
I don’t see the ```operations``` directory under ```config``` when trying to create a commit request using the example [here](https://cdot65.github.io/pan-scm-sdk/sdk/models/operations/candidate_push/).

**Cannot find** -> ```from scm.config.operations import CandidatePush```

I see the ```commit``` and ```get_job_status``` crud methods in the ```scm/config/__init__.py``` file but it looks like the CandidatePush class is missing.

**Comment by cdot65** [comment]
A commit will handle the push, there is no distinction in the SCM product like there is in Panorama. When you commit in SCM, it pushes to the boxes automatically, and this is true via the SDK too

**Comment by mrcloudmustache** [comment]
I understand how the commit process works overall but I'm not able to write the commit code according to your example https://cdot65.github.io/pan-scm-sdk/sdk/models/operations/candidate_push/ in the 'Creating a Commit Request' section. This is because I cannot import the ' CandidatePush' class. I guess what I'm looking for is a working example of how to commit the candidate config to SCM.

**Comment by cdot65** [comment]
As we chatted yesterday, the `.commit()` method is sourced from the base client, so all inherited objects (Address, Service, etc.) will have the method available to them.
